### ISSUE TITLE
Add docker container

### ISSUE THREAD

**Issue by migueLib** [weigertlab/spotiflow#10]
I'm part of the developer team of nf-core/mcmicro an nf-core/nextflow pipeline that transforms multi-channel whole-slide images into single-cell data.  

We would like to integrate spotiflow as a module in the pipeline, to do so we require a docker container. I have already created a docker container with some modifications to the CLI #9  (you can find the docker [here](https://hub.docker.com/repository/docker/miguelib/spotiflow/general).  That said it makes a lot more sense to create a docker container from the original (this) repository, I'm happy to provide  the current dockerfile, the github action to produce the package and any other help.

Thank you! 
Cheers, Miguel :)

**Comment by AlbertDominguez** [comment]
Hi Miguel,

Thanks for this, I think it is very useful!I just checked your forked repo where you did this nice work, looks good! I think it shouldn't be too hard to adapt to the original (this) repo. Feel free to PR some adapted changes (along with or separate from the CLI one) if you have the time, otherwise I'll check and adapt it myself in the following weeks!

**Comment by AlbertDominguez** [comment]
Closed by #11

**Comment by migueLib** [comment]
Hi Albert, I just realized that the container is not yet public. 

Could you change the visibility of the package in package > package settings > Change package visibility?

Thanks a lot!

**Comment by AlbertDominguez** [comment]
Oops sorry, done!
