### ISSUE TITLE
Napari plugin not working

### ISSUE THREAD

**Issue by SebastienTs** [weigertlab/spotiflow#16]
**Describe the bug**
No output shown when using the Napari plugin while the code works when called from the sample inference Python script from GitHub webpage (same image)

**Environment (please complete the following information):**
 - Spotiflow version: latest
 - OS version: Windows 11

**Comment by AlbertDominguez** [comment]
Hi @SebastienTs,

This is probably a known bug related to the napari version (see [this issue](https://github.com/weigertlab/napari-spotiflow/issues/2#issuecomment-2345748034) in the plugin repository).

Could you make sure the napari version and the napari-spotiflow versions are at its latest? In any case, running `pip install -U "napari[all]" spotiflow napari-spotiflow` from the command line interface should suffice as it will install the latest versions for everything. I suggest using a fresh environment if possible, in case other plugins have other `napari` versions dependencies.

Let me know if that does solve it, otherwise we can take a deeper look!

**Comment by SebastienTs** [comment]
Indeed, I was still using Napari 0.4.19 which seems incompatible.
The plugin works with 0.5.3. Thanks for your help!
