### ISSUE TITLE
Recent releases don't have wheels on pypi

### ISSUE THREAD

**Issue by psobolewskiPhD** [weigertlab/spotiflow#18]
**Describe the bug**

When looking at the files on pypi, e.g.:
https://pypi.org/project/spotiflow/0.4.4/#files
There are no wheels for versions newer than 0.4.1

![image](https://github.com/user-attachments/assets/ec981a36-73e9-441c-a7e6-c09af26c07c8)

**Comment by AlbertDominguez** [comment]
Hi @psobolewskiPhD,
Thanks a lot for bringing this up, completely missed this. Will take a look now...

**Comment by AlbertDominguez** [comment]
So it was due to a breaking change in one of the actions... i reverted and released, so `0.4.5` should have the wheels in PyPi. I don't think one can upload files to existing PyPi versions (AFAIK), but the changes in the last versions are very minor so I think it should be fine. Thanks a lot for reporting this 🙂
